### ISSUE TITLE
Viewing {{#AdminLTE}} page overrides global body styles 

### ISSUE THREAD

**Issue by bjimdar** [meteor-factory/meteor-admin-lte#10]
Hey, great job on the nice style theme package. One point of feedback:

I was confused by a weird style bug that one of our testers filed on our site after adding this package to my existing Meteor project and adding a page with an {{#AdminLTE}} section.
#### The "bug" from our perspective, goes like this:

>    **Repro:**
>        1. Load a page in the [existing Meteor] site. Notice styles are normal.
>        2. Load the new page with an {{#AdminLTE}} section.
>        3. Go back to first page loaded in step 1.
> 
>    **Expected:**
>    Styles on the non-AdminLTE page to be the same before and after a page with AdminLTE content is loaded
> 
>    **Actual:** 
>    Styles are all different in the entire Meteor application for the rest of that session.
>    Links are now blue, and fonts have changed and some other stuff.
#### Why this is happening

So it seems the reason for this behavior is that this package is dynamically loading and injecting the AdminLTE.min.css styles into the site the first time the {{#AdminLTE}} section is rendered. 

This permanently dumps a bunch of global style into the site.

``` css
body {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-family: 'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    overflow-x: hidden;
    overflow-y: auto
}
```
#### What might be better

This is cool and all, but I guess I was expecting that any styling added by the package would be limited in it's effects to only content inside the {{#AdminLTE}} {{/AdminLTE}} section blocks.

I understand that you "_just wrote a Meteor wrapper for the AdminLTE package_" and if it's not working for me I can just remove the package and import the original source myself, but I got your package in my app as a dependency of [yogiben:admin](https://atmospherejs.com/yogiben/admin) package. So even if I pull out your package, I still get the same behavior anytime one of my users views the content from that package.

Can styles that cause side-effects outside {{#AdminLTE}} section be removed?
If not, can a setting be added to turn if off for users who don't want their global styles overridden?
